# Generated by Django 3.2 on 2025-06-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.IntegerField(primary_key=True, serialize=False)),
                ('under', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('reg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('contact_person', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('authentication', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('trans_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trans_date', models.DateField()),
                ('typeCode', models.IntegerField()),
                ('amount', models.FloatField()),
                ('narration', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('trans_type', models.IntegerField()),
                ('company_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('category', models.IntegerField()),
                ('date', models.DateField()),
                ('narration', models.CharField(max_length=100)),
                ('typeCode', models.IntegerField(blank=True, null=True)),
                ('company_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.company')),
            ],
        ),
    ]
